### ISSUE TITLE
`!applyref` two functions at a time

### ISSUE THREAD

**Issue by thanhtvt** [speechbrain/HyperPyYAML#18]
Hi, 

Thanks for creating this config tool. I have an use case like this

In Python, I can easily call 2 function at a time like
```python
import datetime
a = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
```
How can I do that in YAML file? I have tried
```yaml
a: !applyref:datetime.datetime.now.strftime
    format: "%Y-%m-%d_%H-%M-%S"

b: !ref <a><a>
```
but it doesn't work.

Any helps are appreciated. Thank you!!

**Comment by thanhtvt** [comment]
I realize I can do something like this
```yaml
a: !applyref:time.strftime
    - "%Y-%m-%d_%H-%M-%S"
    - !applyref:time.gmtime
        - !applyref:time.time

b: !ref <a>
```
